buildscript {
    ext.kotlin_version = '2.1.20'
    ext.compileSdkVersion = 34
    ext.minSdkVersion = 21
    ext.targetSdkVersion = 34
    ext.flutter = [
        compileSdkVersion: 34,
        minSdkVersion: 21,
        targetSdkVersion: 34
    ]
    repositories {
        google()
        mavenCentral()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:8.4.2'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.buildDir = "../build"
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(":app")
}
subprojects {
    project.plugins.whenPluginAdded { plugin ->
        if ("com.android.build.gradle.AppPlugin".equals(plugin.class.name) ||
            "com.android.build.gradle.LibraryPlugin".equals(plugin.class.name)) {
            project.android {
                compileSdkVersion 34
            }
        }
    }
}

tasks.register("clean", Delete) {
    delete rootProject.buildDir
}
